apiVersion: v1
kind: Service
metadata:
  name: simple-web-service
  namespace: testbed
spec:
  ports:
    - name: "8080"
      port: 8082
      targetPort: 8080
  selector:
    app: simple-web
  type: NodePort